# Generated by Django 3.2.9 on 2021-11-09 04:48

from django.db import migrations, models
import uuid
from category.models import Category 


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_id_slug'),
    ]
    
    def gen_uuid(category,schema_editor):
        for row in Category.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),
        
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True)
            ),
    ]
