# Generated by Django 3.2.9 on 2021-11-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_slug_category_slug_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug_category',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
