# Generated by Django 3.2.9 on 2021-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_photoalbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='grade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
