# Generated by Django 3.2.9 on 2021-11-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category_name',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
