# Generated by Django 3.2.9 on 2021-11-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogs_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='category_name',
        ),
        migrations.AddField(
            model_name='blogs',
            name='name_cate',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
